sudo: false
language: node_js
os:
  - linux
  - osx
node_js:
  - "stable"
  - "4.1"
before_install:
  - npm install npm -g
  - npm install svgexport -g
before_script:
  - npm run bootstrap
after_success:
  - npm run lint
