import type { ComputedContentSourceDocumentOpenAPI, RevisionPageDocument } from '@gitbook/api';

/**
 * Get the method and deprecated state of a page generated by the OpenAPI
 * computed source in one-operation-per-page mode.
 */
export function getOpenAPIOperationPageProps(
    page: RevisionPageDocument
): { method: string; deprecated: boolean } | undefined {
    if (!('computed' in page)) {
        return;
    }

    const source = page.computed;
    if (source.type !== 'builtin:openapi') {
        return;
    }

    const { props } = source as ComputedContentSourceDocumentOpenAPI;
    if (props.doc !== 'operation') {
        return;
    }

    return {
        method: props.method,
        deprecated: props.deprecated === true,
    };
}
