import type {
    CacheEntryType,
    CacheValue,
    NextModeTagCacheWriteInput,
    QueueMessage,
} from '@opennextjs/aws/types/overrides.js';
import { getTagsFromValue } from '@opennextjs/aws/utils/cache.js';
import { softTagFilter } from '@opennextjs/cloudflare/overrides/tag-cache/tag-cache-filter';
import { WorkerEntrypoint } from 'cloudflare:workers';

// @ts-ignore Generated by the Cloudflare build.
import { runWithCloudflareRequestContext } from '../../.open-next/cloudflare/init.js';
import { GitbookIncrementalCache } from '../incrementalCache/incrementalCache';
import queue from '../queue/middleware';
import tagCache from '../tagCache/middleware';

type CacheWorkerEnv = {
    WORKER_SELF_REFERENCE: {
        fetch(request: Request): Promise<Response>;
    };
};

const NativeRequest = globalThis.Request;

/**
 * Enters the OpenNext request context, then undoes the one global it patches that this worker
 * cannot live with.
 *
 * `init()` swaps `globalThis.Request` for a subclass that strips `cache` from `RequestInit`, for
 * the benefit of the Next.js server — which runs in the container, not here. Requests the runtime
 * hands us are instances of the native class, so after the swap `request instanceof Request` is
 * false, and `@cloudflare/containers` falls back to treating the request as a URL string
 * (`Invalid URL: [object Request]`). Restoring the native class is safe because `init()` runs
 * synchronously on the way in, so no other task can observe the swapped global.
 */
function runWithCacheContext<T>(
    request: Request,
    env: CacheWorkerEnv,
    ctx: ExecutionContext,
    handler: () => Promise<T>
): Promise<T> {
    const result = runWithCloudflareRequestContext(request, env, ctx, handler);
    globalThis.Request = NativeRequest;
    return result;
}

//@ts-ignore - Just to avoid tag cache crashing
globalThis.openNextConfig = {
    dangerous: {
        enableCacheInterception: true,
    },
};

const cacheEntryTypes = new Set<CacheEntryType>(['cache', 'fetch', 'composable']);

const isCacheEntryType = (value: string | null): value is CacheEntryType =>
    value !== null && cacheEntryTypes.has(value as CacheEntryType);

const NO_STORE_CACHE_CONTROL = 'private, no-store, max-age=0, must-revalidate';
const INTERNAL_PATH = '/internal';
const CACHE_CONTROL_HEADER = 'x-gitbook-cache-control';
const CACHE_TAG_HEADER = 'x-gitbook-cache-tag';

const getCacheHeaders = (cacheControl: string, cacheTag?: string): HeadersInit => ({
    'Cache-Control': cacheControl,
    [CACHE_CONTROL_HEADER]: cacheControl,
    ...(cacheTag
        ? {
              'Cache-Tag': cacheTag,
              [CACHE_TAG_HEADER]: cacheTag,
          }
        : {}),
});

const nullCacheResponse = (hasBeenRevalidated = false): Response =>
    Response.json(null, {
        headers: {
            ...getCacheHeaders(NO_STORE_CACHE_CONTROL),
            ...(hasBeenRevalidated ? { 'x-gitbook-cache-revalidated': 'true' } : {}),
        },
    });

const restoreCacheHeaders = (response: Response): Response => {
    const headers = new Headers(response.headers);
    const cacheControl = headers.get(CACHE_CONTROL_HEADER);
    const cacheTag = headers.get(CACHE_TAG_HEADER);

    if (cacheControl) {
        headers.set('Cache-Control', cacheControl);
    }
    if (cacheTag) {
        headers.set('Cache-Tag', cacheTag);
    }

    return new Response(response.body, {
        status: response.status,
        statusText: response.statusText,
        headers,
    });
};

const isTimeStale = (value: CacheValue<CacheEntryType>, lastModified?: number): boolean => {
    const revalidate = value.revalidate;
    if (typeof revalidate !== 'number') {
        return false;
    }

    return Date.now() >= (lastModified ?? Date.now()) + revalidate * 1000;
};

const getTagName = (tag: NextModeTagCacheWriteInput): string =>
    typeof tag === 'string' ? tag : tag.tag;

/**
 * The cache tier for every server tier: the middleware and the default worker reach it through the
 * `NEXT_INC_CACHE_WORKER` service binding, the container through the outbound handler in
 * `containerOutbound.ts`. It lives in the container worker so container traffic — the tier that
 * reads the cache most — stays within a single worker.
 *
 * It is a named entrypoint so the response cache can be enabled for it alone (see `exports` in
 * `containerWrangler.jsonc`); the default entrypoint serves rendered pages and must not be cached.
 * The Durable Objects it drives stay in the DO worker and are bound here by `script_name`.
 */
export class IncrementalCacheWorker extends WorkerEntrypoint<CacheWorkerEnv> {
    async fetch(request: Request): Promise<Response> {
        if (request.method !== 'GET') {
            return new Response('Method not allowed', { status: 405 });
        }

        const url = new URL(request.url);
        if (url.pathname !== INTERNAL_PATH) {
            url.pathname = INTERNAL_PATH;
            const response = await this.env.WORKER_SELF_REFERENCE.fetch(new Request(url, request));
            return restoreCacheHeaders(response);
        }

        const key = url.searchParams.get('key');
        const cacheType = url.searchParams.get('cacheType');
        if (!key || (cacheType !== null && !isCacheEntryType(cacheType))) {
            return new Response('Invalid cache request', { status: 400 });
        }

        return runWithCacheContext(request, this.env, this.ctx, async () => {
            const value = await new GitbookIncrementalCache().get(key, cacheType ?? undefined);
            if (!value?.value) {
                return nullCacheResponse();
            }

            const tags = getTagsFromValue(value?.value as CacheValue<'cache'> | undefined);
            if (await tagCache.hasBeenRevalidated(tags, value.lastModified)) {
                return nullCacheResponse(true);
            }

            if (isTimeStale(value.value, value.lastModified)) {
                return nullCacheResponse(true);
            }

            return Response.json(value, {
                headers: getCacheHeaders(
                    // 1 hour cache, with a 1 day stale-while-revalidate.
                    'public, s-maxage=3600, stale-while-revalidate=86400',
                    [`incremental-cache:${key}`, ...tags].join(',')
                ),
            });
        });
    }

    async set<CacheType extends CacheEntryType>(
        key: string,
        value: CacheValue<CacheType>,
        cacheType?: CacheType
    ): Promise<void> {
        await this.#runRpcOperation(async () => {
            await new GitbookIncrementalCache().set(key, value, cacheType);
        });
    }

    async delete(key: string): Promise<void> {
        await this.#runRpcOperation(async () => {
            await new GitbookIncrementalCache().delete(key);
        });
    }

    async writeTags(tags: NextModeTagCacheWriteInput[]): Promise<void> {
        const tagsToWrite = tags.filter(softTagFilter);
        if (tagsToWrite.length === 0) {
            return;
        }

        await this.#runRpcOperation(async () => {
            await tagCache.writeTags(tagsToWrite);
            await this.ctx.cache?.purge({ tags: tagsToWrite.map(getTagName) });
        });
    }

    /**
     * The ISR queue Durable Object lives in the DO worker, but the container tier — which has no
     * Cloudflare bindings of its own — enqueues revalidations through here.
     */
    async enqueueRevalidation(msg: QueueMessage): Promise<void> {
        await this.#runRpcOperation(async () => {
            await queue.send(msg);
        });
    }

    async #runRpcOperation(operation: () => Promise<void>): Promise<void> {
        await runWithCacheContext(
            new Request('https://incremental-cache.internal'),
            this.env,
            this.ctx,
            async () => {
                await operation();
                return new Response(null, { status: 204 });
            }
        );
    }
}
