import { DurableObject, WorkerEntrypoint } from 'cloudflare:workers';
import type {
    CacheEntryType,
    CacheValue,
    NextModeTagCacheWriteInput,
} from '@opennextjs/aws/types/overrides.js';
import { getTagsFromValue } from '@opennextjs/aws/utils/cache.js';
import { softTagFilter } from '@opennextjs/cloudflare/overrides/tag-cache/tag-cache-filter';

// @ts-ignore Generated by the Cloudflare build.
import { runWithCloudflareRequestContext } from '../../.open-next/cloudflare/init.js';
import { GitbookIncrementalCache } from '../incrementalCache/incrementalCache';
import tagCache from '../tagCache/middleware';

type CacheWorkerEnv = {
    NEXT_INC_CACHE_R2_BUCKET: {
        put(key: string, value: string): Promise<unknown>;
    };
    WORKER_SELF_REFERENCE: {
        fetch(request: Request): Promise<Response>;
    };
};

//@ts-ignore - Just to avoid tag cache crashing
globalThis.openNextConfig = {
    dangerous: {
        enableCacheInterception: true,
    },
};

const cacheEntryTypes = new Set<CacheEntryType>(['cache', 'fetch', 'composable']);

const isCacheEntryType = (value: string | null): value is CacheEntryType =>
    value !== null && cacheEntryTypes.has(value as CacheEntryType);

const NO_STORE_CACHE_CONTROL = 'private, no-store, max-age=0, must-revalidate';
const INTERNAL_PATH = '/internal';
const CACHE_CONTROL_HEADER = 'x-gitbook-cache-control';
const CACHE_TAG_HEADER = 'x-gitbook-cache-tag';

const getCacheHeaders = (cacheControl: string, cacheTag?: string): HeadersInit => ({
    'Cache-Control': cacheControl,
    [CACHE_CONTROL_HEADER]: cacheControl,
    ...(cacheTag
        ? {
              'Cache-Tag': cacheTag,
              [CACHE_TAG_HEADER]: cacheTag,
          }
        : {}),
});

const nullCacheResponse = (hasBeenRevalidated = false): Response =>
    Response.json(null, {
        headers: {
            ...getCacheHeaders(NO_STORE_CACHE_CONTROL),
            ...(hasBeenRevalidated ? { 'x-gitbook-cache-revalidated': 'true' } : {}),
        },
    });

const restoreCacheHeaders = (response: Response): Response => {
    const headers = new Headers(response.headers);
    const cacheControl = headers.get(CACHE_CONTROL_HEADER);
    const cacheTag = headers.get(CACHE_TAG_HEADER);

    if (cacheControl) {
        headers.set('Cache-Control', cacheControl);
    }
    if (cacheTag) {
        headers.set('Cache-Tag', cacheTag);
    }

    return new Response(response.body, {
        status: response.status,
        statusText: response.statusText,
        headers,
    });
};

const isTimeStale = (value: CacheValue<CacheEntryType>, lastModified?: number): boolean => {
    const revalidate = value.revalidate;
    if (typeof revalidate !== 'number') {
        return false;
    }

    return Date.now() >= (lastModified ?? Date.now()) + revalidate * 1000;
};

const getTagName = (tag: NextModeTagCacheWriteInput): string =>
    typeof tag === 'string' ? tag : tag.tag;

// `use cache` can write the same key concurrently, but R2 accepts one write per key per second.
export class R2WriteBuffer extends DurableObject<CacheWorkerEnv> {
    private writePromise: Promise<unknown> | undefined;

    async write(cacheKey: string, value: string): Promise<void> {
        if (this.writePromise) {
            return;
        }

        const writePromise = this.env.NEXT_INC_CACHE_R2_BUCKET.put(cacheKey, value);
        this.writePromise = writePromise;
        this.ctx.waitUntil(
            writePromise.finally(() => {
                this.writePromise = undefined;
            })
        );
    }
}

// @ts-ignore Generated by the Cloudflare build.
export { DOQueueHandler } from '../../.open-next/.build/durable-objects/queue.js';

// @ts-ignore Generated by the Cloudflare build.
export { DOShardedTagCache } from '../../.open-next/.build/durable-objects/sharded-tag-cache.js';

export default class IncrementalCacheWorker extends WorkerEntrypoint<CacheWorkerEnv> {
    async fetch(request: Request): Promise<Response> {
        if (request.method !== 'GET') {
            return new Response('Method not allowed', { status: 405 });
        }

        const url = new URL(request.url);
        if (url.pathname !== INTERNAL_PATH) {
            url.pathname = INTERNAL_PATH;
            const response = await this.env.WORKER_SELF_REFERENCE.fetch(new Request(url, request));
            return restoreCacheHeaders(response);
        }

        const key = url.searchParams.get('key');
        const cacheType = url.searchParams.get('cacheType');
        if (!key || (cacheType !== null && !isCacheEntryType(cacheType))) {
            return new Response('Invalid cache request', { status: 400 });
        }

        return runWithCloudflareRequestContext(request, this.env, this.ctx, async () => {
            const value = await new GitbookIncrementalCache().get(key, cacheType ?? undefined);
            if (!value?.value) {
                return nullCacheResponse();
            }

            const tags = getTagsFromValue(value?.value as CacheValue<'cache'> | undefined);
            if (await tagCache.hasBeenRevalidated(tags, value.lastModified)) {
                return nullCacheResponse(true);
            }

            if (isTimeStale(value.value, value.lastModified)) {
                return nullCacheResponse(true);
            }

            return Response.json(value, {
                headers: getCacheHeaders(
                    // 1 hour cache, with a 1 day stale-while-revalidate.
                    'public, s-maxage=3600, stale-while-revalidate=86400',
                    [`incremental-cache:${key}`, ...tags].join(',')
                ),
            });
        });
    }

    async set<CacheType extends CacheEntryType>(
        key: string,
        value: CacheValue<CacheType>,
        cacheType?: CacheType
    ): Promise<void> {
        await this.#runRpcOperation(async () => {
            await new GitbookIncrementalCache().set(key, value, cacheType);
        });
    }

    async delete(key: string): Promise<void> {
        await this.#runRpcOperation(async () => {
            await new GitbookIncrementalCache().delete(key);
        });
    }

    async writeTags(tags: NextModeTagCacheWriteInput[]): Promise<void> {
        const tagsToWrite = tags.filter(softTagFilter);
        if (tagsToWrite.length === 0) {
            return;
        }

        await this.#runRpcOperation(async () => {
            await tagCache.writeTags(tagsToWrite);
            await this.ctx.cache?.purge({ tags: tagsToWrite.map(getTagName) });
        });
    }

    async #runRpcOperation(operation: () => Promise<void>): Promise<void> {
        await runWithCloudflareRequestContext(
            new Request('https://incremental-cache.internal'),
            this.env,
            this.ctx,
            async () => {
                await operation();
                return new Response(null, { status: 204 });
            }
        );
    }
}
