import { DurableObject, WorkerEntrypoint } from 'cloudflare:workers';
import type { CacheEntryType, CacheValue } from '@opennextjs/aws/types/overrides.js';
import { getTagsFromValue } from '@opennextjs/aws/utils/cache.js';

// @ts-ignore Generated by the Cloudflare build.
import { runWithCloudflareRequestContext } from '../../.open-next/cloudflare/init.js';
import { GitbookIncrementalCache } from '../incrementalCache/incrementalCache';

type CacheWorkerEnv = {
    NEXT_INC_CACHE_R2_BUCKET: {
        put(key: string, value: string): Promise<unknown>;
    };
};

const cacheEntryTypes = new Set<CacheEntryType>(['cache', 'fetch', 'composable']);

const isCacheEntryType = (value: string | null): value is CacheEntryType =>
    value !== null && cacheEntryTypes.has(value as CacheEntryType);

// `use cache` can write the same key concurrently, but R2 accepts one write per key per second.
export class R2WriteBuffer extends DurableObject<CacheWorkerEnv> {
    private writePromise: Promise<unknown> | undefined;

    async write(cacheKey: string, value: string): Promise<void> {
        if (this.writePromise) {
            return;
        }

        const writePromise = this.env.NEXT_INC_CACHE_R2_BUCKET.put(cacheKey, value);
        this.writePromise = writePromise;
        this.ctx.waitUntil(
            writePromise.finally(() => {
                this.writePromise = undefined;
            })
        );
    }
}

// @ts-ignore Generated by the Cloudflare build.
export { DOQueueHandler } from '../../.open-next/.build/durable-objects/queue.js';

// @ts-ignore Generated by the Cloudflare build.
export { DOShardedTagCache } from '../../.open-next/.build/durable-objects/sharded-tag-cache.js';

export default class IncrementalCacheWorker extends WorkerEntrypoint<CacheWorkerEnv> {
    async fetch(request: Request): Promise<Response> {
        if (request.method !== 'GET') {
            return new Response('Method not allowed', { status: 405 });
        }

        const url = new URL(request.url);
        const key = url.searchParams.get('key');
        const cacheType = url.searchParams.get('cacheType');
        if (!key || (cacheType !== null && !isCacheEntryType(cacheType))) {
            return new Response('Invalid cache request', { status: 400 });
        }

        return runWithCloudflareRequestContext(request, this.env, this.ctx, async () => {
            const value = await new GitbookIncrementalCache().get(key, cacheType ?? undefined);
            const tags = getTagsFromValue(value?.value as CacheValue<'cache'> | undefined);
            return Response.json(value, {
                headers: {
                    'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=3600',
                    'Cache-Tag': [`incremental-cache:${key}`, ...tags].join(','),
                },
            });
        });
    }

    async set<CacheType extends CacheEntryType>(
        key: string,
        value: CacheValue<CacheType>,
        cacheType?: CacheType
    ): Promise<void> {
        await this.#runRpcOperation(async () => {
            await new GitbookIncrementalCache().set(key, value, cacheType);
        });
    }

    async delete(key: string): Promise<void> {
        await this.#runRpcOperation(async () => {
            await new GitbookIncrementalCache().delete(key);
        });
    }

    async #runRpcOperation(operation: () => Promise<void>): Promise<void> {
        await runWithCloudflareRequestContext(
            new Request('https://incremental-cache.internal'),
            this.env,
            this.ctx,
            async () => {
                await operation();
                return new Response(null, { status: 204 });
            }
        );
    }
}
