import { DurableObject } from 'cloudflare:workers';

type CacheWorkerEnv = {
    NEXT_INC_CACHE_R2_BUCKET: {
        put(key: string, value: string): Promise<unknown>;
    };
};

// `use cache` can write the same key concurrently, but R2 accepts one write per key per second.
export class R2WriteBuffer extends DurableObject<CacheWorkerEnv> {
    private writePromise: Promise<unknown> | undefined;

    async write(cacheKey: string, value: string): Promise<void> {
        if (this.writePromise) {
            return;
        }

        const writePromise = this.env.NEXT_INC_CACHE_R2_BUCKET.put(cacheKey, value);
        this.writePromise = writePromise;
        this.ctx.waitUntil(
            writePromise.finally(() => {
                this.writePromise = undefined;
            })
        );
    }
}

// @ts-ignore Generated by the Cloudflare build.
export { DOQueueHandler } from '../../.open-next/.build/durable-objects/queue.js';

// @ts-ignore Generated by the Cloudflare build.
export { DOShardedTagCache } from '../../.open-next/.build/durable-objects/sharded-tag-cache.js';

/**
 * This worker only hosts Durable Objects — the cache tier itself now lives in the container worker
 * (`containerCache.ts`). The handler stays because `DOQueueHandler` requires a
 * `WORKER_SELF_REFERENCE` service binding, which has always pointed back at this worker.
 */
export default {
    fetch(): Response {
        return new Response('Not found', { status: 404 });
    },
};
