import { createHash } from 'node:crypto';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { languageLocales } from '../src/intl/translations';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const translationsDir = join(scriptDir, '../src/intl/translations');
const outputDir = join(scriptDir, '../public/~gitbook/static/translations');
const manifestFile = join(translationsDir, 'assets.ts');

await rm(outputDir, { force: true, recursive: true });
await mkdir(outputDir, { recursive: true });

const assetPaths: string[] = [];

for (const locale of [...languageLocales].sort()) {
    const exportName = locale.replaceAll('-', '_');
    const module = await import(pathToFileURL(join(translationsDir, `${locale}.ts`)).href);
    const translation = module[exportName];

    if (!translation || typeof translation !== 'object') {
        throw new Error(`Translation module ${locale}.ts does not export ${exportName}`);
    }

    const content = `${JSON.stringify(translation)}\n`;
    // Assets are served as immutable for a year, the filename has to change with the content.
    const hash = createHash('sha256').update(content).digest('hex').slice(0, 8);
    const fileName = `${locale}.${hash}.json`;

    await writeFile(join(outputDir, fileName), content);

    // Match the formatter's quoting so the generated file stays stable.
    const key = /^[A-Za-z_$][\w$]*$/.test(locale) ? locale : `'${locale}'`;
    assetPaths.push(`    ${key}: 'translations/${fileName}',`);
}

await writeFile(
    manifestFile,
    [
        '// Generated by scripts/generate-translations.ts, do not edit.',
        '',
        'export const translationAssetPaths: Record<string, string> = {',
        ...assetPaths,
        '};',
        '',
    ].join('\n')
);
