import * as fs from 'node:fs/promises';
import * as path from 'node:path';

/*
 * As a workaround for https://github.com/cloudflare/next-on-pages/issues/880
 * We currently expand the `_headers` generated with our custom headers for static files
 */
const headerPath = path.resolve(process.cwd(), '.vercel/output/static/_headers');

const inputHeaders = await fs.readFile(headerPath, 'utf-8');

const headers = `
${inputHeaders}

# === START AUTOGENERATED GitBook static assets IMMUTABLE HEADERS ===
/~gitbook/static/*
  cache-control: public,max-age=31536000,immutable
# === END AUTOGENERATED GitBook static assets IMMUTABLE HEADERS ===
`;

await fs.writeFile(headerPath, headers);
