main = ".open-next/worker.js"
name = "gitbook-v2"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }
observability = { enabled = true }

[env.preview]
kv_namespaces = [
  { binding = "NEXT_CACHE_WORKERS_KV", id = "gitbook-open-v2-cache-preview" }
]

[env.production]
kv_namespaces = [
  { binding = "NEXT_CACHE_WORKERS_KV", id = "gitbook-open-v2-cache" }
]
