name: Deploy Staging
on:
    push:
        branches:
            - main
jobs:
    deploy-vercel:
        name: Deploy v2 to Vercel
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
            issues: write
            pull-requests: write
            checks: write
            statuses: write
        outputs:
            deployment-url: ${{ steps.deploy.outputs.deployment-url }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Deploy staging
              id: deploy
              uses: ./.github/composite/deploy-vercel
              with:
                  environment: staging
                  vercel-org: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project: ${{ secrets.VERCEL_PROJECT_ID }}
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
    deploy-cloudflare:
        name: Deploy v2 to Cloudflare Worker
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
            issues: write
            pull-requests: write
            checks: write
            statuses: write
        outputs:
            deployment-url: ${{ steps.deploy.outputs.deployment-url }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Deploy
              id: deploy
              uses: ./.github/composite/deploy-cloudflare
              with:
                  environment: staging
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: ${{ secrets.NEXT_SERVER_ACTIONS_ENCRYPTION_KEY }}
                  GITBOOK_URL: ${{ env.STAGING_2C_GITBOOK_URL }}
                  GITBOOK_IMAGE_RESIZE_SIGNING_KEY: ${{ secrets.STAGING_GITBOOK_IMAGE_RESIZE_SIGNING_KEY }}
                  GITBOOK_IMAGE_RESIZE_URL: ${{ env.GITBOOK_IMAGE_RESIZE_URL }}
                  GITBOOK_ICONS_URL: ${{ env.GITBOOK_ICONS_URL }}
                  GITBOOK_ICONS_TOKEN: ${{ env.GITBOOK_ICONS_TOKEN }}
                  GITBOOK_ASSETS_PREFIX: ${{ env.STAGING_2C_GITBOOK_ASSETS_PREFIX }}
            - name: Outputs
              run: |
                  echo "URL: ${{ steps.deploy.outputs.deployment-url }}"